version: '3.9'

services:
  oracle-19c:
    image: doctorkirk/oracle-19c:19.3.0
    container_name: ${NOMBRE:-oracle-stack}
    user: "oracle"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - oracle-net
    ports:
      - "${ORACLE_PORT:-1521}:1521"
    environment:
      - ORACLE_SID=${ORACLE_SID:-ORCLCDB}
      - ORACLE_PWD=${ORACLE_PWD}
      - ORACLE_CHARACTERSET=AL32UTF8
      - NLS_LANG=AMERICAN_AMERICA.AL32UTF8
      - TZ=${TZ:-UTC}
      - INIT_SGA_SIZE=1024
      - INIT_PGA_SIZE=512
      - ENABLE_ARCHIVELOG=${ENABLE_ARCHIVELOG:-false}
    volumes:
      - ${VOLUME_PATH:-./oradata}:/opt/oracle/oradata
      - ${SCRIPT_PATH:-./scripts}:/opt/oracle/scripts
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "@/opt/oracle/scripts/healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  oracle-net:
    driver: bridge